/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/elevator.glb 
Author: Azad Balabanian (https://sketchfab.com/azadbal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elevator-in-berlin-realitiesio-7c759a68446c4bf3b109bfa9cea974ae
Title: Elevator in Berlin - Realities.io
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Elevator(props) {
  const { nodes, materials } = useGLTF('/elevator.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -12, 2]} rotation={[-0.006, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ElevatorCLEAN2_Material_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ElevatorCLEAN2_Material_u1_v2} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ElevatorCLEAN2_Material_u2_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.ElevatorCLEAN2_Material_u2_v2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.ElevatorCLEAN2_Material_u3_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/elevator.glb')
