/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mech_drone.glb 
Author: Willy Decarpentrie (https://sketchfab.com/skudgee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mech-drone-8d06874aac5246c59edb4adbe3606e0e
Title: Mech Drone
*/
'use client'

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function MechDrone(props) {
  const group = React.useRef()
  const { scene,  animations } = useGLTF('/mech_drone.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
  console.log('Material Details:', materials.Robot);
  console.log('Diffuse Map:', materials.Robot?.map);
}, [materials]);


  useEffect(() => {
    // Grab the first available animation action
    const actionName = Object.keys(actions)[0];
    const action = actions[actionName];
    
    if (action) {
      action.reset().fadeIn(0.5).play();
    }
    
    // Optional cleanup on unmount
    return () => {
      if (action) action.fadeOut(0.5);
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
          <group name="DroneFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="droid" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Robot} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mech_drone.glb')
